dinnertime/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from rest_framework import routers
from meals.api import MealViewSet
from users.api import UserViewSet

urlpatterns = patterns('',
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^meals/', include("meals.urls", namespace="meals")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# API related url patterns
router = routers.DefaultRouter()
router.register(r'meals', MealViewSet)
router.register(r'users', UserViewSet)

urlpatterns = urlpatterns + patterns (
    '',
    url(
        r'^api/', 
        include(router.urls)
    ),
)

dinnertime/meals/urls.py
from django.conf.urls import include, patterns, url
from rest_framework import routers

from djgeojson.views import GeoJSONLayerView

from .views import MealList, MealCreate, MealDetail, MealUpdate, MealDelete
from .api import MealViewSet
from .models import Meal


router = routers.DefaultRouter()
router.register(r'meals', MealViewSet)

urlpatterns = patterns(
    '',
    url(
    	r'^$', 
    	MealList.as_view(), 
    	name='meal_list'
    ),
    url(
    	r'^new/$', 
    	MealCreate.as_view(), 
    	name='meal_create'
    ),
    url(
    	r'^(?P<pk>\d+)/$', 
    	MealDetail.as_view(), 
    	name='meal_detail'
    ),
    url(
    	r'^(?P<pk>\d+)/update/$', 
	    MealUpdate.as_view(), 
	    name='meal_update'
    ),
    url(
    	r'^(?P<pk>\d+)/delete/$', 
	    MealDelete.as_view(), 
	    name='meal_delete'
    ),
)


urlpatterns = urlpatterns + patterns('',
    url(r'^data.geojson$', GeoJSONLayerView.as_view(model=Meal), name='geodata')
)

dinnertime/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w\-_]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

dinnertime/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Dinnertime{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

    <!-- Add custom CSS here -->
    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">


    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js"></script>
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Table Surfing</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'about' %}">About</a>
                    </li>
                    {% if request.user.is_authenticated %}
                      <li><a href="{% url 'meals:meal_list' %}">Meals</a>
                      </li>
                      <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
                      <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
                    {% else %}
                      <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
                      <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block extra_body %}

    <div class="container main-container">
        
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        
      {% endblock content %}

    </div> <!-- /container -->

    {% endblock extra_body %}

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#about">About</a>
                        </li>
                        {% if request.user.is_authenticated %}
                          <li class="footer-menu-divider">&sdot;</li>
                          <li><a href="#meals">Meals</a>
                          </li>
                        {% endif %}
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Piemonster Technology. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
    
    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

      <!-- Latest compiled and minified JavaScript -->
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/jquery-1.10.2.js' %}"></script>
      <script src="{% static 'js/bootstrap.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>
 