dinnertime/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from rest_framework import routers
from meals.api import MealViewSet
from users.api import UserViewSet

urlpatterns = patterns('',
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here
    url(r'^meals/', include("meals.urls", namespace="meals")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# API related url patterns
router = routers.DefaultRouter()
router.register(r'meals', MealViewSet)
router.register(r'users', UserViewSet)

urlpatterns = urlpatterns + patterns (
    '',
    url(
        r'^api/', 
        include(router.urls)
    ),
)

dinnertime/meals/urls.py
from django.conf.urls import include, patterns, url
from rest_framework import routers

from djgeojson.views import GeoJSONLayerView

from .views import MealList, MealCreate, MealDetail, MealUpdate, MealDelete
from .api import MealViewSet
from .models import Meal


router = routers.DefaultRouter()
router.register(r'meals', MealViewSet)

urlpatterns = patterns(
    '',
    url(
    	r'^$', 
    	MealList.as_view(), 
    	name='meal_list'
    ),
    url(
    	r'^new/$', 
    	MealCreate.as_view(), 
    	name='meal_create'
    ),
    url(
    	r'^(?P<pk>\d+)/$', 
    	MealDetail.as_view(), 
    	name='meal_detail'
    ),
    url(
    	r'^(?P<pk>\d+)/update/$', 
	    MealUpdate.as_view(), 
	    name='meal_update'
    ),
    url(
    	r'^(?P<pk>\d+)/delete/$', 
	    MealDelete.as_view(), 
	    name='meal_delete'
    ),
)


urlpatterns = urlpatterns + patterns('',
    url(r'^data.geojson$', GeoJSONLayerView.as_view(model=Meal), name='geodata')
)

dinnertime/meals/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.contrib.gis.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from autoslug import AutoSlugField

from users.models import User

@python_2_unicode_compatible
class Meal(models.Model):
    
    """
    Stores Meal objects
    """
    
    # General
    name = models.CharField(_('name'), help_text=_('Name of the meal'), max_length=255)
    slug = AutoSlugField(populate_from='name')
    datetime = models.DateTimeField(_('datetime'), help_text=_('When is the meal?'), blank=True, null=True)

    # User relationships
    created_by = models.ForeignKey(User, help_text=_('Who created the meal?'), related_name='created_meals')
    hosted_by = models.ManyToManyField(User, help_text=_('Who is hosting?'), related_name='hosted_meals' , blank=True, null=True)
    attended_by = models.ManyToManyField(User, help_text=_('Who is coming?'), related_name='attended_meals' , blank=True, null=True)
    declined_by = models.ManyToManyField(User, help_text=_('Who is not coming?'), related_name='declined_meals' , blank=True, null=True)
    invited = models.ManyToManyField(User, help_text=_('Who is invited?'), related_name='invited_meals' , blank=True, null=True)
    
    max_guests = models.IntegerField(_('max_guests'), help_text=_('How many guests can come?'), default=5)

    # Privacy
    hidden = models.BooleanField(_('hidden'), help_text=_('Is the meal a secret?'), default=False)
    invite_only = models.BooleanField(_('invite_only'), help_text=_('Is the meal invite only?'), default=False)

    # GeoDjango-specific:
    objects = models.GeoManager()
    location = models.PointField()

    class Meta:
        verbose_name = _('Meal')
        verbose_name_plural = _('Meals')

    def __str__(self):
        return '{}'.format(self.name or 'Unsaved')

    def get_absolute_url(self):
        return reverse('meals:meal_detail', args=[str(self.id)])

    @property
    def invited_count(self):
        return self.invited.objects.all().count()

    @property
    def attended_count(self):
        return self.attended_by.objects.all().count()

    def invite_user(self, user):
        return self.invited.objects.add(user)

    def attend(self, user):
        if self.invited.objects.contains(user):
            # The user was invited, add them to attended
            self.attended_by.objects.add(user)
            # Remove the user from invited
            self.invited.object.remove(user)

            return "Not implemented"
        else:
            #The user was not invited or has already accepted return an error.
            return "403" # TODO: Look at how this returns

    @property
    def geom(self):
        return self.location

dinnertime/meals/forms.py
import floppyforms as forms

from leaflet.forms.widgets import LeafletWidget

from .models import Meal


class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        widgets = {'where': LeafletWidget()}

dinnertime/meals/views.py
from django.core.urlresolvers import reverse
from vanilla import ListView, CreateView, DetailView, UpdateView, DeleteView
from .forms import MealForm
from .models import Meal


class MealCRUDView(object):

    """
    Provides a mixin for Meal objects
    """

    model = Meal
    form_class = MealForm
    paginate_by = 20

    def get_success_url(self):
        return reverse('meal_list')


class MealList(MealCRUDView, ListView):

    """
    Provides a view to list Meal objects
    """

    pass


class MealCreate(MealCRUDView, CreateView):

    """
    Provides a view to create Meal objects
    """

    pass


class MealDetail(MealCRUDView, DetailView):

    """
    Provides a view to show a specific Meal object
    """

    pass


class MealUpdate(MealCRUDView, UpdateView):

    """
    Provides a view to update a specific Meal object
    """

    pass


class MealDelete(MealCRUDView, DeleteView):

    """
    Provides a view to delete a specific Meal object
    """

    pass

dinnertime/templates/meals/meal_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete</h1>
    <p>Are you sure you want to delete?</p>

    <form id="meal_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-primary" /> <a href="{% url 'meals:meal_list' %}" class="btn btn-danger">No</a>
    </form>
{% endblock %}

dinnertime/templates/meals/meal_detail.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% block content %}
	{% leaflet_js %}
    {% leaflet_css %}
    {% leaflet_map "main" callback="main_map_init" %}

    <script type="text/javascript">
        function main_map_init (map, options) {

            var dataurl = '{% url "meals:geodata" %}';
            // Download GeoJSON via Ajax
            $.getJSON(dataurl, function (data) {
                // Add GeoJSON layer
                L.geoJson(data).addTo(map);
            });

        }
    </script>
    <h1>{{ object.name }}</h1>
    <h3> Hosted by: {% for host in object.hosted_by.all %} {{host}} {% endfor %}  </h3>
    <h3> Confirmed Guests: {% for guest in object.attended_by.all %} {{guest}} {% endfor %}  </h3>
    <h3> Invited Guests: {% for gues in object.invited.all %} {{guest}} {% endfor %}  </h3>
    <a href="{% url 'meals:meal_list' %}">List</a>
{% endblock %}

dinnertime/templates/meals/meal_form.html
{% extends "base.html" %}

{% load crispy_forms_tags leaflet_tags %}

{% block content %}
	{% leaflet_js plugins="forms" %}
    {% leaflet_css plugins="forms" %}

	<div class="container">
	    <div class="row">
	        <div class="col-lg-12">
	            <h1>{% block header %}Create/Update {% endblock %}</h1>
	            <form class="form-horizontal" method="post" action=".">
	                {% csrf_token %}
	                {{ form|crispy }}
	                <div class="control-group">
	                  <div class="controls">
	                    <button type="submit" class="btn">Submit</button>
	                  </div>
	                </div>
	            </form>
	        </div>
	    </div>
	</div>
{% endblock %}

dinnertime/templates/meals/meal_list.html
{% extends "base.html" %}

{% load leaflet_tags %}

{% block content %}
    <h1>Upcoming Meals</h1>
    <a href="{% url 'meals:meal_create' %}">Create</a>
    <ul>
        {% for object in object_list %}
            <li>
                {{ object }}
                <a href="{{ object.get_absolute_url }}">Details</a>
                <a href="{% url 'meals:meal_update' object.pk %}">Update</a>
                <a href="{% url 'meals:meal_delete' object.pk %}">Delete</a>
            </li>
        {% empty %}
                <p>No items.</p>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'meals:meal_list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'meals:meal_list' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}

    {% leaflet_js %}
    {% leaflet_css %}
    {% leaflet_map "main" callback="main_map_init" %}

    <script type="text/javascript">
        function main_map_init (map, options) {

            var dataurl = '{% url "meals:geodata" %}';
            // Download GeoJSON via Ajax
            $.getJSON(dataurl, function (data) {
                // Add GeoJSON layer
                L.geoJson(data).addTo(map);
            });

        }
    </script>


{% endblock %}